version: '3.9'

services:
  nextjs:
    container_name: nextjs-app
    build: .
    ports:
      - '3000:3000'
      - '5555:5555'
    depends_on:
      - db
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run dev

  db:
    container_name: postgres-db
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: database
      POSTGRES_PASSWORD: database
      POSTGRES_DB: database
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'

volumes:
  postgres_data:
