import type { Metadata } from "next";
import { NextIntlClientProvider } from "next-intl";
import { getLocale } from "next-intl/server";
import { Encode_Sans } from "next/font/google";
import CookieConsentBanner from "./cookie-consent-banner";
import "./globals.css";
import { Providers } from "./providers";
import { SessionProvider } from "@/hooks/useSession";
import { auth } from "@/lib/auth";
import { headers } from "next/headers";
import ConditionalHeader from "./conditional-header";

const fontSans = Encode_Sans({
  variable: "--encode-sans",
  subsets: ["latin"],
});

const fontSerif = Encode_Sans({
  variable: "--encode-serif",
  subsets: ["latin"],
});

const fontMono = Encode_Sans({
  variable: "--encode-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

type RawUser = {
  id: string;
  firstname: string | null;
  image: string | null;
};

type RawSession = {
  user: RawUser | null;
} | null;

type SafeUser = {
  id: string;
  firstname?: string;
  image?: string;
};

type SafeSession = {
  user: SafeUser | null;
} | null;

function cleanSession(rawSession: RawSession): SafeSession {
  if (!rawSession) return null;
  const user = rawSession.user;

  return {
    user: user
      ? {
          id: user.id,
          firstname: user.firstname ?? undefined,
          image: user.image ?? undefined,
        }
      : null,
  };
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const locale = await getLocale();
  const rawSession = await auth.api.getSession({
    headers: await headers(),
  });

  const session = cleanSession(rawSession);

  return (
    <html lang={locale} suppressHydrationWarning>
      <body
        className={`${fontSans.variable} ${fontSerif.variable} ${fontMono.variable} antialiased`}
        suppressHydrationWarning
      >
        <NextIntlClientProvider>
          <SessionProvider initialSession={session}>
            <Providers>
              <CookieConsentBanner />
              <ConditionalHeader />
              {children}
            </Providers>
          </SessionProvider>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
