import type { Metadata } from "next";
import { NextIntlClientProvider } from "next-intl";
import { getLocale } from "next-intl/server";
import { Encode_Sans } from "next/font/google";
import CookieConsentBanner from "./cookie-consent-banner";
import "./globals.css";
import { Providers } from "./providers";

const fontSans = Encode_Sans({
  variable: "--encode-sans",
  subsets: ["latin"],
});

const fontSerif = Encode_Sans({
  variable: "--encode-serif",
  subsets: ["latin"],
});

const fontMono = Encode_Sans({
  variable: "--encode-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const locale = await getLocale();

  return (
    <html lang={locale} suppressHydrationWarning>
      <body
        className={`${fontSans.variable} ${fontSerif.variable} ${fontMono.variable} antialiased`}
        suppressHydrationWarning
      >
        <NextIntlClientProvider>
          <Providers>
            <CookieConsentBanner />
            {children}
          </Providers>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
